# Generated by Django 4.2.16 on 2024-12-03 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(max_length=50, verbose_name='Tipo Empleado')),
            ],
            options={
                'db_table': 'type_users',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='DNI')),
                ('birthdate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('surname', models.CharField(max_length=20, verbose_name='Apellido')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=54, verbose_name='Email')),
                ('direction', models.CharField(max_length=250, verbose_name='Dirección')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/%Y/%m/%d')),
                ('type_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.type_user')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['id'],
            },
        ),
    ]
