# Generated by Django 4.2.16 on 2024-11-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_payment_invoice_payment_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CANCELED', 'CANCELED'), ('PENDING', 'PENDING'), ('PAID', 'PAID'), ('INVOICED', 'INVOICED')], max_length=10),
        ),
    ]
